# Generated by Django 3.0.8 on 2020-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_vector_balanca'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.CharField(default='NC', max_length=80),
        ),
        migrations.AddField(
            model_name='vector',
            name='password',
            field=models.CharField(default='ouinclusivo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vector',
            name='username',
            field=models.CharField(default='adm', max_length=50),
            preserve_default=False,
        ),
    ]
