# Generated by Django 3.0.8 on 2020-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200709_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='cel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='NC', max_length=80),
        ),
        migrations.AddField(
            model_name='vector',
            name='cnum',
            field=models.IntegerField(default=0),
        ),
    ]
